{
  "name": "HealthcareClaimsAnalytics",
  "compatibilityLevel": 1601,
  "model": {
    "culture": "en-US",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Monthly Summary",
        "columns": [
          {"name": "Month", "dataType": "dateTime", "sourceColumn": "month", "formatString": "MMM yyyy"},
          {"name": "Claims", "dataType": "int64", "sourceColumn": "claims", "formatString": "#,0"},
          {"name": "Paid Amount", "dataType": "decimal", "sourceColumn": "total_paid", "formatString": "$#,0.00;($#,0.00);$#,0.00"}
        ],
        "measures": [
          {"name": "Total Claims", "expression": "SUM('Monthly Summary'[Claims])", "formatString": "#,0"},
          {"name": "Total Paid", "expression": "SUM('Monthly Summary'[Paid Amount])", "formatString": "$#,0,,.0M"},
          {"name": "Paid per Claim", "expression": "DIVIDE([Total Paid], [Total Claims])", "formatString": "$#,0"}
        ],
        "partitions": [{"name": "Monthly Summary", "mode": "import", "source": {"type": "m", "expression": ["let", "    Source = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/raghuvardhan-mutha/healthcare-claims-analytics/main/dashboards/data_marts/executive_summary.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),", "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),", "    Typed = Table.TransformColumnTypes(Headers, {{\"month\", type date}, {\"claims\", Int64.Type}, {\"total_paid\", Currency.Type}})", "in", "    Typed"]}}]
      },
      {
        "name": "Claims Status",
        "columns": [
          {"name": "Claim Status", "dataType": "string", "sourceColumn": "claim_status"},
          {"name": "Claims", "dataType": "int64", "sourceColumn": "claims", "formatString": "#,0"}
        ],
        "measures": [
          {"name": "Status Claims", "expression": "SUM('Claims Status'[Claims])", "formatString": "#,0"}
        ],
        "partitions": [{"name": "Claims Status", "mode": "import", "source": {"type": "m", "expression": ["let", "    Source = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/raghuvardhan-mutha/healthcare-claims-analytics/main/dashboards/data_marts/claims_by_status.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),", "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),", "    Typed = Table.TransformColumnTypes(Headers, {{\"claim_status\", type text}, {\"claims\", Int64.Type}})", "in", "    Typed"]}}]
      },
      {
        "name": "Specialty Financials",
        "columns": [
          {"name": "Specialty", "dataType": "string", "sourceColumn": "specialty"},
          {"name": "Claims", "dataType": "int64", "sourceColumn": "claims", "formatString": "#,0"},
          {"name": "Paid Amount", "dataType": "decimal", "sourceColumn": "total_paid", "formatString": "$#,0.00;($#,0.00);$#,0.00"}
        ],
        "measures": [
          {"name": "Specialty Claims", "expression": "SUM('Specialty Financials'[Claims])", "formatString": "#,0"},
          {"name": "Specialty Total Paid", "expression": "SUM('Specialty Financials'[Paid Amount])", "formatString": "$#,0,,.0M"},
          {"name": "Specialty Paid per Claim", "expression": "DIVIDE([Specialty Total Paid], [Specialty Claims])", "formatString": "$#,0"}
        ],
        "partitions": [{"name": "Specialty Financials", "mode": "import", "source": {"type": "m", "expression": ["let", "    Source = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/raghuvardhan-mutha/healthcare-claims-analytics/main/dashboards/data_marts/financial_by_specialty.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),", "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),", "    Typed = Table.TransformColumnTypes(Headers, {{\"specialty\", type text}, {\"claims\", Int64.Type}, {\"total_paid\", Currency.Type}})", "in", "    Typed"]}}]
      },
      {
        "name": "Provider Performance",
        "columns": [
          {"name": "Provider ID", "dataType": "string", "sourceColumn": "provider_id"},
          {"name": "Provider Name", "dataType": "string", "sourceColumn": "provider_name"},
          {"name": "Specialty", "dataType": "string", "sourceColumn": "specialty"},
          {"name": "Claims", "dataType": "int64", "sourceColumn": "claims", "formatString": "#,0"},
          {"name": "Paid Amount", "dataType": "decimal", "sourceColumn": "total_paid", "formatString": "$#,0.00;($#,0.00);$#,0.00"},
          {"name": "Average Paid", "dataType": "decimal", "sourceColumn": "avg_paid", "formatString": "$#,0.00"}
        ],
        "measures": [
          {"name": "Provider Claims", "expression": "SUM('Provider Performance'[Claims])", "formatString": "#,0"},
          {"name": "Provider Total Paid", "expression": "SUM('Provider Performance'[Paid Amount])", "formatString": "$#,0,,.0M"},
          {"name": "Provider Average Paid", "expression": "DIVIDE([Provider Total Paid], [Provider Claims])", "formatString": "$#,0"}
        ],
        "partitions": [{"name": "Provider Performance", "mode": "import", "source": {"type": "m", "expression": ["let", "    Source = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/raghuvardhan-mutha/healthcare-claims-analytics/main/dashboards/data_marts/provider_performance.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),", "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),", "    Typed = Table.TransformColumnTypes(Headers, {{\"provider_id\", type text}, {\"provider_name\", type text}, {\"specialty\", type text}, {\"claims\", Int64.Type}, {\"total_paid\", Currency.Type}, {\"avg_paid\", Currency.Type}})", "in", "    Typed"]}}]
      },
      {
        "name": "Chronic Conditions",
        "columns": [
          {"name": "Condition", "dataType": "string", "sourceColumn": "condition_name"},
          {"name": "Beneficiaries Affected", "dataType": "int64", "sourceColumn": "beneficiaries_affected", "formatString": "#,0"},
          {"name": "Prevalence Pct", "dataType": "decimal", "sourceColumn": "prevalence_pct", "formatString": "0.00"}
        ],
        "measures": [
          {"name": "Total Beneficiaries Affected", "expression": "SUM('Chronic Conditions'[Beneficiaries Affected])", "formatString": "#,0"},
          {"name": "Average Prevalence Pct", "expression": "AVERAGE('Chronic Conditions'[Prevalence Pct])", "formatString": "0.00"}
        ],
        "partitions": [{"name": "Chronic Conditions", "mode": "import", "source": {"type": "m", "expression": ["let", "    Source = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/raghuvardhan-mutha/healthcare-claims-analytics/main/dashboards/data_marts/patient_chronic_conditions.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),", "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),", "    Typed = Table.TransformColumnTypes(Headers, {{\"condition_name\", type text}, {\"beneficiaries_affected\", Int64.Type}, {\"prevalence_pct\", type number}})", "in", "    Typed"]}}]
      },
      {
        "name": "Payment Integrity",
        "columns": [
          {"name": "Provider ID", "dataType": "string", "sourceColumn": "provider_id"},
          {"name": "Provider Name", "dataType": "string", "sourceColumn": "provider_name"},
          {"name": "Specialty", "dataType": "string", "sourceColumn": "specialty"},
          {"name": "Average Lines per Claim", "dataType": "decimal", "sourceColumn": "avg_line_items_per_claim", "formatString": "0.00"},
          {"name": "Potential Unbundled Claims", "dataType": "int64", "sourceColumn": "unbundled_claims", "formatString": "#,0"},
          {"name": "Potential Duplicate Groups", "dataType": "int64", "sourceColumn": "duplicate_groups", "formatString": "#,0"},
          {"name": "Cost vs Peer Ratio", "dataType": "decimal", "sourceColumn": "cost_vs_peer_ratio", "formatString": "0.00"},
          {"name": "Composite Risk Score", "dataType": "decimal", "sourceColumn": "composite_risk_score", "formatString": "0.00"}
        ],
        "measures": [
          {"name": "Review Providers", "expression": "COUNTROWS('Payment Integrity')", "formatString": "#,0"},
          {"name": "Total Potential Unbundled Claims", "expression": "SUM('Payment Integrity'[Potential Unbundled Claims])", "formatString": "#,0"},
          {"name": "Total Potential Duplicate Groups", "expression": "SUM('Payment Integrity'[Potential Duplicate Groups])", "formatString": "#,0"},
          {"name": "Average Cost vs Peer", "expression": "AVERAGE('Payment Integrity'[Cost vs Peer Ratio])", "formatString": "0.00"},
          {"name": "Average Risk Score", "expression": "AVERAGE('Payment Integrity'[Composite Risk Score])", "formatString": "0.00"}
        ],
        "partitions": [{"name": "Payment Integrity", "mode": "import", "source": {"type": "m", "expression": ["let", "    Source = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/raghuvardhan-mutha/healthcare-claims-analytics/main/dashboards/data_marts/fraud_risk_providers.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),", "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),", "    Typed = Table.TransformColumnTypes(Headers, {{\"provider_id\", type text}, {\"provider_name\", type text}, {\"specialty\", type text}, {\"avg_line_items_per_claim\", type number}, {\"unbundled_claims\", Int64.Type}, {\"duplicate_groups\", Int64.Type}, {\"cost_vs_peer_ratio\", type number}, {\"composite_risk_score\", type number}})", "in", "    Typed"]}}]
      }
    ],
    "annotations": [
      {"name": "PBI_QueryOrder", "value": "[\"Monthly Summary\",\"Claims Status\",\"Specialty Financials\",\"Provider Performance\",\"Chronic Conditions\",\"Payment Integrity\"]"},
      {"name": "PBI_ProTooling", "value": "[\"DevMode\"]"}
    ]
  }
}
