-- Run with a role allowed to create databases, warehouses, and schemas.
CREATE DATABASE IF NOT EXISTS HEALTHCARE_CLAIMS_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_CLAIMS_ANALYTICS.ANALYTICS;
CREATE WAREHOUSE IF NOT EXISTS CLAIMS_ANALYTICS_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE CLAIMS_ANALYTICS_WH;
USE DATABASE HEALTHCARE_CLAIMS_ANALYTICS;
USE SCHEMA ANALYTICS;

CREATE FILE FORMAT IF NOT EXISTS CLAIMS_CSV_FORMAT
    TYPE = CSV
    PARSE_HEADER = TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL');

CREATE STAGE IF NOT EXISTS CLAIMS_STAGE
    FILE_FORMAT = CLAIMS_CSV_FORMAT;
