USE DATABASE HEALTHCARE_CLAIMS_ANALYTICS;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY NUMBER(8,0) PRIMARY KEY,
    CALENDAR_DATE DATE NOT NULL,
    YEAR NUMBER(4,0),
    MONTH_NUMBER NUMBER(2,0),
    YEAR_MONTH VARCHAR(7),
    MONTH_NAME VARCHAR(12),
    QUARTER NUMBER(1,0)
);

CREATE OR REPLACE TABLE DIM_MEMBER (
    MEMBER_KEY NUMBER(18,0) PRIMARY KEY,
    BENEFICIARY_ID VARCHAR(20) NOT NULL,
    BIRTH_DATE DATE,
    DEATH_DATE DATE,
    SEX VARCHAR(10),
    RACE VARCHAR(30),
    STATE VARCHAR(2),
    COUNTY_CODE VARCHAR(5),
    ESRD_INDICATOR BOOLEAN,
    PART_A_COVERAGE_MONTHS NUMBER(2,0),
    PART_B_COVERAGE_MONTHS NUMBER(2,0),
    HMO_COVERAGE_MONTHS NUMBER(2,0),
    PART_D_COVERAGE_MONTHS NUMBER(2,0),
    CONSTRAINT UQ_DIM_MEMBER_ID UNIQUE (BENEFICIARY_ID)
);

CREATE OR REPLACE TABLE DIM_PROVIDER (
    PROVIDER_KEY NUMBER(18,0) PRIMARY KEY,
    PROVIDER_ID VARCHAR(20) NOT NULL,
    PROVIDER_NAME VARCHAR(150),
    SPECIALTY VARCHAR(100),
    PROVIDER_TYPE VARCHAR(50),
    STATE VARCHAR(2),
    CONSTRAINT UQ_DIM_PROVIDER_ID UNIQUE (PROVIDER_ID)
);

CREATE OR REPLACE TABLE FACT_CLAIM (
    CLAIM_KEY VARCHAR(50) PRIMARY KEY,
    CLAIM_ID VARCHAR(20) NOT NULL,
    CLAIM_TYPE VARCHAR(20) NOT NULL,
    SERVICE_DATE_KEY NUMBER(8,0) REFERENCES DIM_DATE(DATE_KEY),
    MEMBER_KEY NUMBER(18,0) REFERENCES DIM_MEMBER(MEMBER_KEY),
    PROVIDER_KEY NUMBER(18,0) REFERENCES DIM_PROVIDER(PROVIDER_KEY),
    DRG_CODE VARCHAR(10),
    SUBMITTED_DATE DATE,
    RECEIVED_DATE DATE,
    ADJUDICATED_DATE DATE,
    PAYMENT_DATE DATE,
    BILLED_AMOUNT NUMBER(14,2),
    ALLOWED_AMOUNT NUMBER(14,2),
    PAID_AMOUNT NUMBER(14,2),
    MEMBER_RESPONSIBILITY_AMOUNT NUMBER(14,2),
    ADJUDICATION_STATUS VARCHAR(20),
    DENIAL_REASON_CODE VARCHAR(10),
    SOURCE_TRANSACTION VARCHAR(10),
    REMITTANCE_TRANSACTION VARCHAR(10),
    SUBMISSION_TYPE VARCHAR(20),
    APPEAL_INDICATOR BOOLEAN,
    IS_INJECTED_SIGNAL BOOLEAN,
    INJECTED_PATTERN VARCHAR(40),
    ADJUDICATION_DAYS NUMBER(6,0)
);

CREATE OR REPLACE TABLE BRIDGE_CLAIM_DIAGNOSIS (
    CLAIM_KEY VARCHAR(50) REFERENCES FACT_CLAIM(CLAIM_KEY),
    DIAGNOSIS_CODE VARCHAR(10),
    DIAGNOSIS_SEQUENCE NUMBER(3,0),
    PRIMARY KEY (CLAIM_KEY, DIAGNOSIS_SEQUENCE)
);

CREATE OR REPLACE TABLE FACT_CLAIM_PROCEDURE (
    CLAIM_KEY VARCHAR(50) REFERENCES FACT_CLAIM(CLAIM_KEY),
    PROCEDURE_CODE VARCHAR(10),
    PROCEDURE_SEQUENCE NUMBER(3,0),
    LINE_CHARGE_AMOUNT NUMBER(14,2),
    PRIMARY KEY (CLAIM_KEY, PROCEDURE_SEQUENCE)
);

COMMENT ON TABLE FACT_CLAIM IS
    'Synthetic portfolio fact table for operational and financial analysis; not for clinical or fraud determinations.';
