-- Upload the generated files with SnowSQL from the repository root:
-- PUT file://data/snowflake/*.csv @HEALTHCARE_CLAIMS_ANALYTICS.ANALYTICS.CLAIMS_STAGE
--     AUTO_COMPRESS=TRUE OVERWRITE=TRUE;

USE WAREHOUSE CLAIMS_ANALYTICS_WH;
USE DATABASE HEALTHCARE_CLAIMS_ANALYTICS;
USE SCHEMA ANALYTICS;

TRUNCATE TABLE DIM_DATE;
TRUNCATE TABLE DIM_MEMBER;
TRUNCATE TABLE DIM_PROVIDER;
TRUNCATE TABLE FACT_CLAIM;
TRUNCATE TABLE BRIDGE_CLAIM_DIAGNOSIS;
TRUNCATE TABLE FACT_CLAIM_PROCEDURE;

COPY INTO DIM_DATE FROM @CLAIMS_STAGE/dim_date.csv
    FILE_FORMAT=(FORMAT_NAME=CLAIMS_CSV_FORMAT) MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE;
COPY INTO DIM_MEMBER FROM @CLAIMS_STAGE/dim_member.csv
    FILE_FORMAT=(FORMAT_NAME=CLAIMS_CSV_FORMAT) MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE;
COPY INTO DIM_PROVIDER FROM @CLAIMS_STAGE/dim_provider.csv
    FILE_FORMAT=(FORMAT_NAME=CLAIMS_CSV_FORMAT) MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE;
COPY INTO FACT_CLAIM FROM @CLAIMS_STAGE/fact_claim.csv
    FILE_FORMAT=(FORMAT_NAME=CLAIMS_CSV_FORMAT) MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE;
COPY INTO BRIDGE_CLAIM_DIAGNOSIS FROM @CLAIMS_STAGE/bridge_claim_diagnosis.csv
    FILE_FORMAT=(FORMAT_NAME=CLAIMS_CSV_FORMAT) MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE;
COPY INTO FACT_CLAIM_PROCEDURE FROM @CLAIMS_STAGE/fact_claim_procedure.csv
    FILE_FORMAT=(FORMAT_NAME=CLAIMS_CSV_FORMAT) MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE;
