USE DATABASE HEALTHCARE_CLAIMS_ANALYTICS;
USE SCHEMA ANALYTICS;

-- Each query must return zero rows or a zero count before BI publication.
SELECT COUNT(*) AS INVALID_FINANCIAL_ORDER
FROM FACT_CLAIM
WHERE PAID_AMOUNT > ALLOWED_AMOUNT OR ALLOWED_AMOUNT > BILLED_AMOUNT;

SELECT COUNT(*) AS INVALID_ADJUDICATION_SEQUENCE
FROM FACT_CLAIM
WHERE RECEIVED_DATE < SUBMITTED_DATE
   OR ADJUDICATED_DATE < RECEIVED_DATE
   OR (PAYMENT_DATE IS NOT NULL AND PAYMENT_DATE < ADJUDICATED_DATE);

SELECT COUNT(*) AS ORPHAN_PROVIDER_KEYS
FROM FACT_CLAIM f
LEFT JOIN DIM_PROVIDER p ON f.PROVIDER_KEY = p.PROVIDER_KEY
WHERE p.PROVIDER_KEY IS NULL;

SELECT COUNT(*) AS ORPHAN_MEMBER_KEYS
FROM FACT_CLAIM f
LEFT JOIN DIM_MEMBER m ON f.MEMBER_KEY = m.MEMBER_KEY
WHERE m.MEMBER_KEY IS NULL;

SELECT CLAIM_KEY, COUNT(*) AS DUPLICATE_ROWS
FROM FACT_CLAIM
GROUP BY CLAIM_KEY
HAVING COUNT(*) > 1;

SELECT CLAIM_TYPE, COUNT(*) AS CLAIMS, SUM(PAID_AMOUNT) AS TOTAL_PAID
FROM FACT_CLAIM
GROUP BY CLAIM_TYPE
ORDER BY CLAIM_TYPE;
